local addonName, LRPMIB = ...;

local L = {};
LRPMIB.L = L;

local function defaultFunc(L, key)
 -- If this function was called, we have no localization for this key.
 -- We could complain loudly to allow localizers to see the error of their ways, 
 -- but, for now, just return the key as its own localization. This allows you to—avoid writing the default localization out explicitly.
 return key;
end
setmetatable(L, {__index=defaultFunc});

local LOCALE = GetLocale()

--all locales
L["CM_CLASS_WARRIOR"] = GetClassInfo(1)
L["CM_CLASS_PALADIN"] = GetClassInfo(2)
L["CM_CLASS_HUNTER"] = GetClassInfo(3)
L["CM_CLASS_ROGUE"] = GetClassInfo(4)
L["CM_CLASS_PRIEST"] = GetClassInfo(5)
L["CM_CLASS_DEATHKNIGHT"] = GetClassInfo(6)
L["CM_CLASS_SHAMAN"] = GetClassInfo(7)
L["CM_CLASS_MAGE"] = GetClassInfo(8)
L["CM_CLASS_WARLOCK"] = GetClassInfo(9)
L["CM_CLASS_MONK"] = GetClassInfo(10)
L["CM_CLASS_DRUID"] = GetClassInfo(11)
L["CM_CLASS_DEMONHUNTER"] = GetClassInfo(12)
L["CM_CLASS_EVOKER"] = GetClassInfo(13)

if LOCALE == "enUS" then
	-- The EU English game client also
	-- uses the US English locale code.
	L["TOC_Title"] = "Icon Browser"
	L["TOC_Notes"] = "A replacement icon browser for macros, bank, and transmog with a search bar and preset filters."

	-- DataTagInfo.db2
	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draenei"
	L["ICON_CATEGORY_DWARVEN"] = "Dwarven"
	L["ICON_CATEGORY_ELVEN"] = "Elven"
	L["ICON_CATEGORY_GNOMISH"] = "Gnomish"
	L["ICON_CATEGORY_GOBLIN"] = "Goblin"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Human"
	L["ICON_CATEGORY_ORCISH"] = "Orcish"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Troll"
	L["ICON_CATEGORY_UNDEAD"] = "Undead"
	L["ICON_CATEGORY_VULPERA"] = "Vulpera"
	L["ICON_CATEGORY_WORGEN"] = "Worgen"

	-- ItemSubClass.db2
	L["ICON_CATEGORY_AXE"] = "Axe"
	L["ICON_CATEGORY_DAGGER"] = "Dagger"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Fist Weapon"
	L["ICON_CATEGORY_MACE"] = "Mace"
	L["ICON_CATEGORY_POLEARM"] = "Polearm"
	L["ICON_CATEGORY_STAFF"] = "Staff"
	L["ICON_CATEGORY_SWORD"] = "Sword"
	L["ICON_CATEGORY_WAND"] = "Wand"
	L["ICON_CATEGORY_WARGLAIVE"] = "Warglaive"

	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO

	-- ItemSubClass.db2
	L["ICON_CATEGORY_BOW"] = "Bow"
	L["ICON_CATEGORY_CROSSBOW"] = "Crossbow"
	L["ICON_CATEGORY_GUN"] = "Gun"
	L["ICON_CATEGORY_THROWN"] = "Thrown"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Cloth"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Leather"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Mail"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Plate"
	

	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD -- offhand
	L["ICON_CATEGORY_SHIELD"] = "Shield" -- ItemSubClass.db2
	
	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Fel" -- DataTagInfo.db2 66
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Void" -- DataTagInfo.db2 75

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alchemy" --CHARACTER_PROFESSION_ALCHEMY
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Archaeology"--PROFESSIONS_ARCHAEOLOGY
	L["ICON_CATEGORY_BLACKSMITHING"] = "Blacksmithing" --CHARACTER_PROFESSION_BLACKSMITHING
	L["ICON_CATEGORY_COOKING"] = "Cooking" --PROFESSIONS_COOKING
	L["ICON_CATEGORY_ENCHANTING"] = "Enchanting" --CHARACTER_PROFESSION_ENCHANTING
	L["ICON_CATEGORY_ENGINEERING"] = "Engineering" --CHARACTER_PROFESSION_ENGINEERING
	L["ICON_CATEGORY_FIRST_AID"] = "First Aid" --PROFESSIONS_FIRST_AID
	L["ICON_CATEGORY_FISHING"] = "Fishing" --PROFESSIONS_FISHING
	L["ICON_CATEGORY_HERBALISM"] = "Herbalism" --CHARACTER_PROFESSION_HERBALISM
	L["ICON_CATEGORY_INSCRIPTION"] = "Inscription" --CHARACTER_PROFESSION_INSCRIPTION
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Jewelcrafting" --CHARACTER_PROFESSION_JEWELCRAFTING
	L["ICON_CATEGORY_LEATHERWORKING"] = "Leatherworking" --CHARACTER_PROFESSION_LEATHERWORKING
	L["ICON_CATEGORY_MINING"] = "Mining" --CHARACTER_PROFESSION_MINING
	L["ICON_CATEGORY_SKINNING"] = "Skinning" --CHARACTER_PROFESSION_SKINNING
	L["ICON_CATEGORY_TAILORING"] = "Tailoring" --CHARACTER_PROFESSION_TAILORING

	-- Item Categories
	L["ICON_CATEGORY_DRINK"] = "Drink"
	L["ICON_CATEGORY_FOOD"] = "Food"
	L["ICON_CATEGORY_MOUNT"] = "Mount"
	L["ICON_CATEGORY_PET"] = "Companions"
	L["ICON_CATEGORY_POTION"] = "Potion"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Trade Goods"

	-- ItemClass.db2
	L["ICON_CATEGORY_HOUSING"] = "Housing"
	L["ICON_CATEGORY_PROFESSION"] = "Professions"
	L["ICON_CATEGORY_ARMOR"] = "Armor"
	L["ICON_CATEGORY_WEAPON"] = "Weapon"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Classes" --ITEM_CLASSES_ALLOWED

	L["ICON_CATEGORY_CULTURE"] = "Culture" -- DataTagGroup.db2

	--unofficial
	L["ICON_CATEGORY_ALLWEAPONS"] = "All Weapons"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Melee Weapons"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Ranged Weapons"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Inventory Slots"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	--unofficial
	L["ICON_CATEGORY_FACTIONS"] = "Factions"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "All Professions"
	L["ICON_CATEGORY_ALLITEMS"] = "All Items"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	-- unofficial
	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Other Factions"
	L["ICON_CATEGORY_JEWELRY"] = "Jewelry"
	L["UnknownIcon"] = "Unknown Icon"
	L["FileID"] = "File ID: %s"

return end

if LOCALE == "esMX" then
-- Spanish (Mexico) translations go here
	L["TOC_Title"] = "Navegador de iconos (Icon Browser)"
	L["TOC_Notes"] = "Un navegador de iconos alternativo para macros, banco y transfiguración con una barra de búsqueda y filtros preestablecidos."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draenei"
	L["ICON_CATEGORY_DWARVEN"] = "Enanos"
	L["ICON_CATEGORY_ELVEN"] = "Elfos"
	L["ICON_CATEGORY_GNOMISH"] = "Gnomos"
	L["ICON_CATEGORY_GOBLIN"] = "Goblin"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Humanos"
	L["ICON_CATEGORY_ORCISH"] = "Orcos"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Trols"
	L["ICON_CATEGORY_UNDEAD"] = "No-muertos"
	L["ICON_CATEGORY_VULPERA"] = "Vulperas"
	L["ICON_CATEGORY_WORGEN"] = "Gilneanos / Huargen"

	L["ICON_CATEGORY_AXE"] = "Hacha"
	L["ICON_CATEGORY_DAGGER"] = "Daga"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Arma de puño"
	L["ICON_CATEGORY_MACE"] = "Maza"
	L["ICON_CATEGORY_POLEARM"] = "Arma de asta"
	L["ICON_CATEGORY_STAFF"] = "Bastón"
	L["ICON_CATEGORY_SWORD"] = "Espada"
	L["ICON_CATEGORY_WAND"] = "Varita"
	L["ICON_CATEGORY_WARGLAIVE"] = "Gujas de guerra"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Arco"
	L["ICON_CATEGORY_CROSSBOW"] = "Ballesta"
	L["ICON_CATEGORY_GUN"] = "Arma de fuego"
	L["ICON_CATEGORY_THROWN"] = "Arma arrojadiza"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Tela"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Cuero"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Malla"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Placas"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Escudo"
	
	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Vil"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Vacío"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alquimia"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Arqueología"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Herrería"
	L["ICON_CATEGORY_COOKING"] = "Cocina"
	L["ICON_CATEGORY_ENCHANTING"] = "Encantamiento"
	L["ICON_CATEGORY_ENGINEERING"] = "Ingeniería"
	L["ICON_CATEGORY_FIRST_AID"] = "Primeros auxilios"
	L["ICON_CATEGORY_FISHING"] = "Pesca"
	L["ICON_CATEGORY_HERBALISM"] = "Herboristería"
	L["ICON_CATEGORY_INSCRIPTION"] = "Inscripción"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Joyería"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Peletería"
	L["ICON_CATEGORY_MINING"] = "Minería"
	L["ICON_CATEGORY_SKINNING"] = "Desuello"
	L["ICON_CATEGORY_TAILORING"] = "Sastrería"

	L["ICON_CATEGORY_DRINK"] = "Bebida"
	L["ICON_CATEGORY_FOOD"] = "Comida"
	L["ICON_CATEGORY_MOUNT"] = "Monturas"
	L["ICON_CATEGORY_PET"] = "Compañeros"
	L["ICON_CATEGORY_POTION"] = "Pociones"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Objetos comerciables"
	L["ICON_CATEGORY_HOUSING"] = "Viviendas"
	L["ICON_CATEGORY_PROFESSION"] = "Profesión"
	L["ICON_CATEGORY_ARMOR"] = "Armadura"
	L["ICON_CATEGORY_WEAPON"] = "Arma"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Clases"
	L["ICON_CATEGORY_CULTURE"] = "Cultura"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Todas las armas"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Armas cuerpo a cuerpo"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Armas a distancia"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Ranuras de inventario"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Facciones"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Todas las profesiones"
	L["ICON_CATEGORY_ALLITEMS"] = "Todos los objetos"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Otras facciones"
	L["ICON_CATEGORY_JEWELRY"] = "Joyería"
	L["UnknownIcon"] = "Icono desconocido"
	L["FileID"] = "ID de archivo: %s"


return end

if LOCALE == "esES" then
	-- Spanish translations go here
	L["TOC_Title"] = "Navegador de iconos (Icon Browser)"
	L["TOC_Notes"] = "Un navegador de iconos alternativo para macros, banco y transfiguración con una barra de búsqueda y filtros preestablecidos."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draenei"
	L["ICON_CATEGORY_DWARVEN"] = "Enanos"
	L["ICON_CATEGORY_ELVEN"] = "Elfos"
	L["ICON_CATEGORY_GNOMISH"] = "Gnomos"
	L["ICON_CATEGORY_GOBLIN"] = "Goblins"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Humanos"
	L["ICON_CATEGORY_ORCISH"] = "Orcos"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Trols"
	L["ICON_CATEGORY_UNDEAD"] = "No-muertos"
	L["ICON_CATEGORY_VULPERA"] = "Vulpera"
	L["ICON_CATEGORY_WORGEN"] = "Gilneanos/huargen"

	L["ICON_CATEGORY_AXE"] = "Hacha"
	L["ICON_CATEGORY_DAGGER"] = "Daga"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Arma de puño"
	L["ICON_CATEGORY_MACE"] = "Maza"
	L["ICON_CATEGORY_POLEARM"] = "Arma de asta"
	L["ICON_CATEGORY_STAFF"] = "Bastón"
	L["ICON_CATEGORY_SWORD"] = "Espada"
	L["ICON_CATEGORY_WAND"] = "Varita"
	L["ICON_CATEGORY_WARGLAIVE"] = "Gujas de guerra"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Arco"
	L["ICON_CATEGORY_CROSSBOW"] = "Ballesta"
	L["ICON_CATEGORY_GUN"] = "Arma de fuego"
	L["ICON_CATEGORY_THROWN"] = "Arma arrojadiza"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Tela"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Cuero"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Malla"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Placas"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Escudo"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Viles"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Vacío"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alquimia"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Arqueología"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Herrería"
	L["ICON_CATEGORY_COOKING"] = "Cocina"
	L["ICON_CATEGORY_ENCHANTING"] = "Encantamiento"
	L["ICON_CATEGORY_ENGINEERING"] = "Ingeniería"
	L["ICON_CATEGORY_FIRST_AID"] = "Primeros auxilios"
	L["ICON_CATEGORY_FISHING"] = "Pesca"
	L["ICON_CATEGORY_HERBALISM"] = "Herboristería"
	L["ICON_CATEGORY_INSCRIPTION"] = "Inscripción"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Joyería"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Peletería"
	L["ICON_CATEGORY_MINING"] = "Minería"
	L["ICON_CATEGORY_SKINNING"] = "Desuello"
	L["ICON_CATEGORY_TAILORING"] = "Sastrería"

	L["ICON_CATEGORY_DRINK"] = "Bebida"
	L["ICON_CATEGORY_FOOD"] = "Comida"
	L["ICON_CATEGORY_MOUNT"] = "Monturas"
	L["ICON_CATEGORY_PET"] = "Compañeros"
	L["ICON_CATEGORY_POTION"] = "Pociones"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Objetos comerciables"
	L["ICON_CATEGORY_HOUSING"] = "Hogares"
	L["ICON_CATEGORY_PROFESSION"] = "Profesión"
	L["ICON_CATEGORY_ARMOR"] = "Armadura"
	L["ICON_CATEGORY_WEAPON"] = "Arma"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Clases"
	L["ICON_CATEGORY_CULTURE"] = "Cultura"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Todas las armas"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Armas cuerpo a cuerpo"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Armas a distancia"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Ranuras de inventario"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Facciones"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Todas las profesiones"
	L["ICON_CATEGORY_ALLITEMS"] = "Todos los objetos"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Otras facciones"
	L["ICON_CATEGORY_JEWELRY"] = "Joyería"
	L["UnknownIcon"] = "Icono desconocido"
	L["FileID"] = "ID de archivo: %s"

return end

if LOCALE == "deDE" then
	-- German translations go here
	L["TOC_Title"] = "Symbolbrowser (Icon Browser)"
	L["TOC_Notes"] = "Ein Ersatz-Iconbrowser für Makros, Bank und Transmog mit Suchleiste und voreingestellten Filtern."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draenei"
	L["ICON_CATEGORY_DWARVEN"] = "Zwerge"
	L["ICON_CATEGORY_ELVEN"] = "Elfen"
	L["ICON_CATEGORY_GNOMISH"] = "Gnome"
	L["ICON_CATEGORY_GOBLIN"] = "Goblins"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Menschen"
	L["ICON_CATEGORY_ORCISH"] = "Orcs"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Trolle"
	L["ICON_CATEGORY_UNDEAD"] = "Untote"
	L["ICON_CATEGORY_VULPERA"] = "Vulpera"
	L["ICON_CATEGORY_WORGEN"] = "Gilneas / Worgen"

	L["ICON_CATEGORY_AXE"] = "Axt"
	L["ICON_CATEGORY_DAGGER"] = "Dolch"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Faustwaffe"
	L["ICON_CATEGORY_MACE"] = "Streitkolben"
	L["ICON_CATEGORY_POLEARM"] = "Stangenwaffe"
	L["ICON_CATEGORY_STAFF"] = "Stab"
	L["ICON_CATEGORY_SWORD"] = "Schwert"
	L["ICON_CATEGORY_WAND"] = "Zauberstab"
	L["ICON_CATEGORY_WARGLAIVE"] = "Kriegsgleven"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Bogen"
	L["ICON_CATEGORY_CROSSBOW"] = "Armbrust"
	L["ICON_CATEGORY_GUN"] = "Schusswaffe"
	L["ICON_CATEGORY_THROWN"] = "Wurfwaffe"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Stoff"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Leder"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Kette"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Platte"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Schild"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Dämonisch"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Leere"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alchemie"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Archäologie"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Schmiedekunst"
	L["ICON_CATEGORY_COOKING"] = "Kochkunst"
	L["ICON_CATEGORY_ENCHANTING"] = "Verzauberkunst"
	L["ICON_CATEGORY_ENGINEERING"] = "Ingenieurskunst"
	L["ICON_CATEGORY_FIRST_AID"] = "Erste Hilfe"
	L["ICON_CATEGORY_FISHING"] = "Angeln"
	L["ICON_CATEGORY_HERBALISM"] = "Kräuterkunde"
	L["ICON_CATEGORY_INSCRIPTION"] = "Inschriftenkunde"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Juwelierskunst"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Lederverarbeitung"
	L["ICON_CATEGORY_MINING"] = "Bergbau"
	L["ICON_CATEGORY_SKINNING"] = "Kürschnerei"
	L["ICON_CATEGORY_TAILORING"] = "Schneiderei"

	L["ICON_CATEGORY_DRINK"] = "Trinken"
	L["ICON_CATEGORY_FOOD"] = "Essen"
	L["ICON_CATEGORY_MOUNT"] = "Reittiere"
	L["ICON_CATEGORY_PET"] = "Haustiere"
	L["ICON_CATEGORY_POTION"] = "Tränke"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Handwerkswaren"
	L["ICON_CATEGORY_HOUSING"] = "Behausung"
	L["ICON_CATEGORY_PROFESSION"] = "Beruf"
	L["ICON_CATEGORY_ARMOR"] = "Rüstung"
	L["ICON_CATEGORY_WEAPON"] = "Waffe"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Klassen"
	L["ICON_CATEGORY_CULTURE"] = "Kultur"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Alle Waffen"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Nahkampfwaffen"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Fernkampfwaffen"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Inventarplätze"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Fraktionen"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Alle Berufe"
	L["ICON_CATEGORY_ALLITEMS"] = "Alle Gegenstände"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Andere Fraktionen"
	L["ICON_CATEGORY_JEWELRY"] = "Schmuck"
	L["UnknownIcon"] = "Unbekanntes Symbol"
	L["FileID"] = "Datei-ID: %s"

return end

if LOCALE == "frFR" then
	-- French translations go here
	L["TOC_Title"] = "Navigateur d’icônes (Icon Browser)"
	L["TOC_Notes"] = "Un navigateur d’icônes de remplacement pour macros, banque et transmogrification avec une barre de recherche et des filtres prédéfinis."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draeneï"
	L["ICON_CATEGORY_DWARVEN"] = "Nain"
	L["ICON_CATEGORY_ELVEN"] = "Elfe"
	L["ICON_CATEGORY_GNOMISH"] = "Gnome"
	L["ICON_CATEGORY_GOBLIN"] = "Gobelin"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Humain"
	L["ICON_CATEGORY_ORCISH"] = "Orc"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Troll"
	L["ICON_CATEGORY_UNDEAD"] = "Mort-vivant"
	L["ICON_CATEGORY_VULPERA"] = "Vulpérin"
	L["ICON_CATEGORY_WORGEN"] = "Gilnéas/Worgen"

	L["ICON_CATEGORY_AXE"] = "Hache"
	L["ICON_CATEGORY_DAGGER"] = "Dague"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Arme de pugilat"
	L["ICON_CATEGORY_MACE"] = "Masse"
	L["ICON_CATEGORY_POLEARM"] = "Arme d’hast"
	L["ICON_CATEGORY_STAFF"] = "Bâton"
	L["ICON_CATEGORY_SWORD"] = "Epée"
	L["ICON_CATEGORY_WAND"] = "Baguette"
	L["ICON_CATEGORY_WARGLAIVE"] = "Glaives de guerre"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Arc"
	L["ICON_CATEGORY_CROSSBOW"] = "Arbalète"
	L["ICON_CATEGORY_GUN"] = "Arme à feu"
	L["ICON_CATEGORY_THROWN"] = "Armes de jet"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Tissu"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Cuir"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Mailles"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Plaques"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Bouclier"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Corruption"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Vide"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alchimie"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Archéologie"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Forge"
	L["ICON_CATEGORY_COOKING"] = "Cuisine"
	L["ICON_CATEGORY_ENCHANTING"] = "Enchantement"
	L["ICON_CATEGORY_ENGINEERING"] = "Ingénierie"
	L["ICON_CATEGORY_FIRST_AID"] = "Secourisme"
	L["ICON_CATEGORY_FISHING"] = "Pêche"
	L["ICON_CATEGORY_HERBALISM"] = "Herboristerie"
	L["ICON_CATEGORY_INSCRIPTION"] = "Calligraphie"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Joaillerie"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Travail du cuir"
	L["ICON_CATEGORY_MINING"] = "Minage"
	L["ICON_CATEGORY_SKINNING"] = "Dépeçage"
	L["ICON_CATEGORY_TAILORING"] = "Couture"

	L["ICON_CATEGORY_DRINK"] = "Boissons"
	L["ICON_CATEGORY_FOOD"] = "Nourriture"
	L["ICON_CATEGORY_MOUNT"] = "Montures"
	L["ICON_CATEGORY_PET"] = "Compagnons"
	L["ICON_CATEGORY_POTION"] = "Potions"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Artisanat"
	L["ICON_CATEGORY_HOUSING"] = "Logis"
	L["ICON_CATEGORY_PROFESSION"] = "Métier"
	L["ICON_CATEGORY_ARMOR"] = "Armure"
	L["ICON_CATEGORY_WEAPON"] = "Arme"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Classes"
	L["ICON_CATEGORY_CULTURE"] = "Culture"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Toutes les armes"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Armes de mêlée"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Armes à distance"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Emplacements d’inventaire"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Factions"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Toutes les professions"
	L["ICON_CATEGORY_ALLITEMS"] = "Tous les objets"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Autres factions"
	L["ICON_CATEGORY_JEWELRY"] = "Bijoux"
	L["UnknownIcon"] = "Icône inconnue"
	L["FileID"] = "ID du fichier : %s"

return end

if LOCALE == "itIT" then
	-- Italian translations go here
	L["TOC_Title"] = "Browser delle icone (Icon Browser)"
	L["TOC_Notes"] = "Un browser di icone sostitutivo per macro, banca e trasmogrificazione con una barra di ricerca e filtri preimpostati."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draenei"
	L["ICON_CATEGORY_DWARVEN"] = "Nanica"
	L["ICON_CATEGORY_ELVEN"] = "Elfica"
	L["ICON_CATEGORY_GNOMISH"] = "Gnomesca"
	L["ICON_CATEGORY_GOBLIN"] = "Goblin"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Umana"
	L["ICON_CATEGORY_ORCISH"] = "Orchesca"
	L["ICON_CATEGORY_PANDAREN"] = "Pandaren"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Troll"
	L["ICON_CATEGORY_UNDEAD"] = "Non Morta"
	L["ICON_CATEGORY_VULPERA"] = "Vulpera"
	L["ICON_CATEGORY_WORGEN"] = "Gilneana/Worgen"

	L["ICON_CATEGORY_AXE"] = "Ascia"
	L["ICON_CATEGORY_DAGGER"] = "Pugnale"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Tirapugni"
	L["ICON_CATEGORY_MACE"] = "Mazza"
	L["ICON_CATEGORY_POLEARM"] = "Arma ad asta"
	L["ICON_CATEGORY_STAFF"] = "Bastone"
	L["ICON_CATEGORY_SWORD"] = "Spada"
	L["ICON_CATEGORY_WAND"] = "Bacchetta"
	L["ICON_CATEGORY_WARGLAIVE"] = "Lame da Guerra"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Arco"
	L["ICON_CATEGORY_CROSSBOW"] = "Balestra"
	L["ICON_CATEGORY_GUN"] = "Arma da fuoco"
	L["ICON_CATEGORY_THROWN"] = "Arma da lancio"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Stoffa"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Cuoio"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Maglia"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Piastre"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Scudo"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Vile"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Vuoto"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alchimia"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Archeologia"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Forgiatura"
	L["ICON_CATEGORY_COOKING"] = "Cucina"
	L["ICON_CATEGORY_ENCHANTING"] = "Incantamento"
	L["ICON_CATEGORY_ENGINEERING"] = "Ingegneria"
	L["ICON_CATEGORY_FIRST_AID"] = "Primo Soccorso"
	L["ICON_CATEGORY_FISHING"] = "Pesca"
	L["ICON_CATEGORY_HERBALISM"] = "Erbalismo"
	L["ICON_CATEGORY_INSCRIPTION"] = "Runografia"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Oreficeria"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Conciatura"
	L["ICON_CATEGORY_MINING"] = "Estrazione"
	L["ICON_CATEGORY_SKINNING"] = "Scuoiatura"
	L["ICON_CATEGORY_TAILORING"] = "Sartoria"

	L["ICON_CATEGORY_DRINK"] = "Bevande"
	L["ICON_CATEGORY_FOOD"] = "Cibi"
	L["ICON_CATEGORY_MOUNT"] = "Cavalcature"
	L["ICON_CATEGORY_PET"] = "Mascotte"
	L["ICON_CATEGORY_POTION"] = "Pozioni"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Beni Commerciali"
	L["ICON_CATEGORY_HOUSING"] = "Alloggi"
	L["ICON_CATEGORY_PROFESSION"] = "Professione"
	L["ICON_CATEGORY_ARMOR"] = "Armature"
	L["ICON_CATEGORY_WEAPON"] = "Arma"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Classi"
	L["ICON_CATEGORY_CULTURE"] = "Cultura"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Tutte le armi"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Armi da mischia"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Armi a distanza"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Slot dell’inventario"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Fazioni"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Tutte le professioni"
	L["ICON_CATEGORY_ALLITEMS"] = "Tutti gli oggetti"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Altre fazioni"
	L["ICON_CATEGORY_JEWELRY"] = "Gioielleria"
	L["UnknownIcon"] = "Icona sconosciuta"
	L["FileID"] = "ID file: %s"

return end

if LOCALE == "ptBR" then
	-- Brazilian Portuguese translations go here
	L["TOC_Title"] = "Navegador de ícones (Icon Browser)"
	L["TOC_Notes"] = "Um navegador de ícones substituto para macros, banco e transmogrificação com barra de pesquisa e filtros predefinidos."

	L["ICON_CATEGORY_DRACTHYR"] = "Dracthyr"
	L["ICON_CATEGORY_DRAENEI"] = "Draeneico"
	L["ICON_CATEGORY_DWARVEN"] = "Enânico"
	L["ICON_CATEGORY_ELVEN"] = "Élfico"
	L["ICON_CATEGORY_GNOMISH"] = "Gnômico"
	L["ICON_CATEGORY_GOBLIN"] = "Goblínico"
	L["ICON_CATEGORY_HARANIR"] = "Haranir"
	L["ICON_CATEGORY_HUMAN"] = "Humano"
	L["ICON_CATEGORY_ORCISH"] = "Órquico"
	L["ICON_CATEGORY_PANDAREN"] = "Pandarênico"
	L["ICON_CATEGORY_TAUREN"] = "Tauren"
	L["ICON_CATEGORY_TROLL"] = "Trólico"
	L["ICON_CATEGORY_UNDEAD"] = "Morto-vivo"
	L["ICON_CATEGORY_VULPERA"] = "Vulperino"
	L["ICON_CATEGORY_WORGEN"] = "Guilneano/Worgen"

	L["ICON_CATEGORY_AXE"] = "Machado"
	L["ICON_CATEGORY_DAGGER"] = "Adaga"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Arma de Punho"
	L["ICON_CATEGORY_MACE"] = "Maça"
	L["ICON_CATEGORY_POLEARM"] = "Arma de Haste"
	L["ICON_CATEGORY_STAFF"] = "Cajado"
	L["ICON_CATEGORY_SWORD"] = "Espada"
	L["ICON_CATEGORY_WAND"] = "Varinha"
	L["ICON_CATEGORY_WARGLAIVE"] = "Glaives de Guerra"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Arco"
	L["ICON_CATEGORY_CROSSBOW"] = "Besta"
	L["ICON_CATEGORY_GUN"] = "Arma de fogo"
	L["ICON_CATEGORY_THROWN"] = "Arremesso"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Tecido"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Couro"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Malha"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Placas"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Escudo"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Vil"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Caos"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Alquimia"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Arqueologia"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Ferraria"
	L["ICON_CATEGORY_COOKING"] = "Culinária"
	L["ICON_CATEGORY_ENCHANTING"] = "Encantamento"
	L["ICON_CATEGORY_ENGINEERING"] = "Engenharia"
	L["ICON_CATEGORY_FIRST_AID"] = "Primeiros socorros"
	L["ICON_CATEGORY_FISHING"] = "Pesca"
	L["ICON_CATEGORY_HERBALISM"] = "Herborismo"
	L["ICON_CATEGORY_INSCRIPTION"] = "Escrivania"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Joalheria"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Couraria"
	L["ICON_CATEGORY_MINING"] = "Mineração"
	L["ICON_CATEGORY_SKINNING"] = "Esfolamento"
	L["ICON_CATEGORY_TAILORING"] = "Alfaiataria"

	L["ICON_CATEGORY_DRINK"] = "Bebidas"
	L["ICON_CATEGORY_FOOD"] = "Comidas"
	L["ICON_CATEGORY_MOUNT"] = "Montarias"
	L["ICON_CATEGORY_PET"] = "Mascotes"
	L["ICON_CATEGORY_POTION"] = "Poções"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Bens de Comércio"
	L["ICON_CATEGORY_HOUSING"] = "Moradia"
	L["ICON_CATEGORY_PROFESSION"] = "Profissão"
	L["ICON_CATEGORY_ARMOR"] = "Armadura"
	L["ICON_CATEGORY_WEAPON"] = "Arma"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Classes"
	L["ICON_CATEGORY_CULTURE"] = "Cultura"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Todas as armas"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Armas corpo a corpo"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Armas de longo alcance"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Espaços do inventário"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Facções"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Todas as profissões"
	L["ICON_CATEGORY_ALLITEMS"] = "Todos os itens"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Outras facções"
	L["ICON_CATEGORY_JEWELRY"] = "Joias"
	L["UnknownIcon"] = "Ícone desconhecido"
	L["FileID"] = "ID do arquivo: %s"

-- Note that the EU Portuguese WoW client also
-- uses the Brazilian Portuguese locale code.
return end

if LOCALE == "ruRU" then
	-- Russian translations go here
	L["TOC_Title"] = "Браузер значков (Icon Browser)"
	L["TOC_Notes"] = "Замена браузера значков для макросов, банка и трансмогрификации с строкой поиска и предустановленными фильтрами."

	L["ICON_CATEGORY_DRACTHYR"] = "Драктиры"
	L["ICON_CATEGORY_DRAENEI"] = "Дренеи"
	L["ICON_CATEGORY_DWARVEN"] = "Дворфы"
	L["ICON_CATEGORY_ELVEN"] = "Эльфы"
	L["ICON_CATEGORY_GNOMISH"] = "Гномы"
	L["ICON_CATEGORY_GOBLIN"] = "Гоблины"
	L["ICON_CATEGORY_HARANIR"] = "Хараниры"
	L["ICON_CATEGORY_HUMAN"] = "Люди"
	L["ICON_CATEGORY_ORCISH"] = "Орки"
	L["ICON_CATEGORY_PANDAREN"] = "Пандарены"
	L["ICON_CATEGORY_TAUREN"] = "Таурены"
	L["ICON_CATEGORY_TROLL"] = "Тролли"
	L["ICON_CATEGORY_UNDEAD"] = "Нежить"
	L["ICON_CATEGORY_VULPERA"] = "Вульперы"
	L["ICON_CATEGORY_WORGEN"] = "Гилнеас (воргены)"

	L["ICON_CATEGORY_AXE"] = "Топор"
	L["ICON_CATEGORY_DAGGER"] = "Кинжал"
	L["ICON_CATEGORY_FIST_WEAPON"] = "Кистевое"
	L["ICON_CATEGORY_MACE"] = "Дробящее"
	L["ICON_CATEGORY_POLEARM"] = "Древковое"
	L["ICON_CATEGORY_STAFF"] = "Посох"
	L["ICON_CATEGORY_SWORD"] = "Меч"
	L["ICON_CATEGORY_WAND"] = "Жезл"
	L["ICON_CATEGORY_WARGLAIVE"] = "Боевые клинки"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "Лук"
	L["ICON_CATEGORY_CROSSBOW"] = "Арбалет"
	L["ICON_CATEGORY_GUN"] = "Огнестрельное"
	L["ICON_CATEGORY_THROWN"] = "Метательное"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "Ткань"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "Кожа"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "Кольчуга"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "Латы"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "Щит"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "Скверна"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "Бездна"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "Алхимия"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "Археология"
	L["ICON_CATEGORY_BLACKSMITHING"] = "Кузнечное дело"
	L["ICON_CATEGORY_COOKING"] = "Кулинария"
	L["ICON_CATEGORY_ENCHANTING"] = "Наложение чар"
	L["ICON_CATEGORY_ENGINEERING"] = "Инженерное дело"
	L["ICON_CATEGORY_FIRST_AID"] = "Первая помощь"
	L["ICON_CATEGORY_FISHING"] = "Рыбная ловля"
	L["ICON_CATEGORY_HERBALISM"] = "Травничество"
	L["ICON_CATEGORY_INSCRIPTION"] = "Начертание"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "Ювелирное дело"
	L["ICON_CATEGORY_LEATHERWORKING"] = "Кожевничество"
	L["ICON_CATEGORY_MINING"] = "Горное дело"
	L["ICON_CATEGORY_SKINNING"] = "Снятие шкур"
	L["ICON_CATEGORY_TAILORING"] = "Портняжное дело"

	L["ICON_CATEGORY_DRINK"] = "Напитки"
	L["ICON_CATEGORY_FOOD"] = "Еда"
	L["ICON_CATEGORY_MOUNT"] = "Средства передвижения"
	L["ICON_CATEGORY_PET"] = "Спутники"
	L["ICON_CATEGORY_POTION"] = "Зелья"
	L["ICON_CATEGORY_TRADE_GOODS"] = "Хозяйственные товары"
	L["ICON_CATEGORY_HOUSING"] = "Жилье"
	L["ICON_CATEGORY_PROFESSION"] = "Профессия"
	L["ICON_CATEGORY_ARMOR"] = "Доспехи"
	L["ICON_CATEGORY_WEAPON"] = "Оружие"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "Классы"
	L["ICON_CATEGORY_CULTURE"] = "Культура"

	L["ICON_CATEGORY_ALLWEAPONS"] = "Все оружие"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "Оружие ближнего боя"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "Оружие дальнего боя"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "Ячейки инвентаря"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "Фракции"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "Все профессии"
	L["ICON_CATEGORY_ALLITEMS"] = "Все предметы"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "Другие фракции"
	L["ICON_CATEGORY_JEWELRY"] = "Ювелирные изделия"
	L["UnknownIcon"] = "Неизвестный значок"
	L["FileID"] = "ID файла: %s"

return end

if LOCALE == "koKR" then
	-- Korean translations go here
	L["TOC_Title"] = "아이콘 브라우저 (Icon Browser)"
	L["TOC_Notes"] = "매크로, 은행, 형상변환용 아이콘 브라우저 대체, 검색창과 사전 설정 필터 포함."

	L["ICON_CATEGORY_DRACTHYR"] = "드랙티르"
	L["ICON_CATEGORY_DRAENEI"] = "드레나이"
	L["ICON_CATEGORY_DWARVEN"] = "드워프"
	L["ICON_CATEGORY_ELVEN"] = "엘프"
	L["ICON_CATEGORY_GNOMISH"] = "노움"
	L["ICON_CATEGORY_GOBLIN"] = "고블린"
	L["ICON_CATEGORY_HARANIR"] = "하라니르"
	L["ICON_CATEGORY_HUMAN"] = "인간"
	L["ICON_CATEGORY_ORCISH"] = "오크"
	L["ICON_CATEGORY_PANDAREN"] = "판다렌"
	L["ICON_CATEGORY_TAUREN"] = "타우렌"
	L["ICON_CATEGORY_TROLL"] = "트롤"
	L["ICON_CATEGORY_UNDEAD"] = "언데드"
	L["ICON_CATEGORY_VULPERA"] = "불페라"
	L["ICON_CATEGORY_WORGEN"] = "길니아스 / 늑대인간"

	L["ICON_CATEGORY_AXE"] = "도끼"
	L["ICON_CATEGORY_DAGGER"] = "단검"
	L["ICON_CATEGORY_FIST_WEAPON"] = "장착 무기"
	L["ICON_CATEGORY_MACE"] = "둔기"
	L["ICON_CATEGORY_POLEARM"] = "장창"
	L["ICON_CATEGORY_STAFF"] = "지팡이"
	L["ICON_CATEGORY_SWORD"] = "도검"
	L["ICON_CATEGORY_WAND"] = "마법봉"
	L["ICON_CATEGORY_WARGLAIVE"] = "전투검"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "활"
	L["ICON_CATEGORY_CROSSBOW"] = "석궁"
	L["ICON_CATEGORY_GUN"] = "총"
	L["ICON_CATEGORY_THROWN"] = "투척 무기"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "천"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "가죽"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "사슬"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "판금"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "방패"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "지옥"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "공허"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "연금술"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "고고학"
	L["ICON_CATEGORY_BLACKSMITHING"] = "대장기술"
	L["ICON_CATEGORY_COOKING"] = "요리"
	L["ICON_CATEGORY_ENCHANTING"] = "마법부여"
	L["ICON_CATEGORY_ENGINEERING"] = "기계공학"
	L["ICON_CATEGORY_FIRST_AID"] = "응급치료"
	L["ICON_CATEGORY_FISHING"] = "낚시"
	L["ICON_CATEGORY_HERBALISM"] = "약초채집"
	L["ICON_CATEGORY_INSCRIPTION"] = "주문각인"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "보석세공"
	L["ICON_CATEGORY_LEATHERWORKING"] = "가죽세공"
	L["ICON_CATEGORY_MINING"] = "채광"
	L["ICON_CATEGORY_SKINNING"] = "무두질"
	L["ICON_CATEGORY_TAILORING"] = "재봉술"

	L["ICON_CATEGORY_DRINK"] = "음료"
	L["ICON_CATEGORY_FOOD"] = "음식"
	L["ICON_CATEGORY_MOUNT"] = "탈것들"
	L["ICON_CATEGORY_PET"] = "비전투 애완동물들"
	L["ICON_CATEGORY_POTION"] = "물약"
	L["ICON_CATEGORY_TRADE_GOODS"] = "거래 용품"
	L["ICON_CATEGORY_HOUSING"] = "하우징"
	L["ICON_CATEGORY_PROFESSION"] = "전문 기술"
	L["ICON_CATEGORY_ARMOR"] = "방어구"
	L["ICON_CATEGORY_WEAPON"] = "무기"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON


	L["ICON_CATEGORY_CLASSES"] = "직업"
	L["ICON_CATEGORY_CULTURE"] = "문화"

	L["ICON_CATEGORY_ALLWEAPONS"] = "모든 무기"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "근접 무기"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "원거리 무기"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "가방 칸"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "진영"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "모든 전문 기술"
	L["ICON_CATEGORY_ALLITEMS"] = "모든 아이템"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "기타 진영"
	L["ICON_CATEGORY_JEWELRY"] = "보석"
	L["UnknownIcon"] = "알 수 없는 아이콘"
	L["FileID"] = "파일 ID: %s"

return end

if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	L["TOC_Title"] = "图标浏览器 (Icon Browser)"
	L["TOC_Notes"] = "用于宏、银行和幻化的图标浏览器替代工具，带搜索栏和预设过滤器。"

	L["ICON_CATEGORY_DRACTHYR"] = "希尔"
	L["ICON_CATEGORY_DRAENEI"] = "德莱尼"
	L["ICON_CATEGORY_DWARVEN"] = "矮人"
	L["ICON_CATEGORY_ELVEN"] = "精灵"
	L["ICON_CATEGORY_GNOMISH"] = "侏儒"
	L["ICON_CATEGORY_GOBLIN"] = "地精"
	L["ICON_CATEGORY_HARANIR"] = "哈籁尼尔"
	L["ICON_CATEGORY_HUMAN"] = "人类"
	L["ICON_CATEGORY_ORCISH"] = "兽人"
	L["ICON_CATEGORY_PANDAREN"] = "熊猫人"
	L["ICON_CATEGORY_TAUREN"] = "牛头人"
	L["ICON_CATEGORY_TROLL"] = "巨魔"
	L["ICON_CATEGORY_UNDEAD"] = "亡灵"
	L["ICON_CATEGORY_VULPERA"] = "狐人"
	L["ICON_CATEGORY_WORGEN"] = "吉尔尼斯人/狼人"

	L["ICON_CATEGORY_AXE"] = "斧"
	L["ICON_CATEGORY_DAGGER"] = "匕首"
	L["ICON_CATEGORY_FIST_WEAPON"] = "拳套"
	L["ICON_CATEGORY_MACE"] = "锤"
	L["ICON_CATEGORY_POLEARM"] = "长柄武器"
	L["ICON_CATEGORY_STAFF"] = "法杖"
	L["ICON_CATEGORY_SWORD"] = "剑"
	L["ICON_CATEGORY_WAND"] = "魔杖"
	L["ICON_CATEGORY_WARGLAIVE"] = "战刃"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "弓"
	L["ICON_CATEGORY_CROSSBOW"] = "弩"
	L["ICON_CATEGORY_GUN"] = "枪械"
	L["ICON_CATEGORY_THROWN"] = "投掷武器"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "布甲"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "皮甲"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "锁甲"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "板甲"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "盾牌"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "邪能"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "虚空"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "炼金术"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "考古学"
	L["ICON_CATEGORY_BLACKSMITHING"] = "锻造"
	L["ICON_CATEGORY_COOKING"] = "烹饪"
	L["ICON_CATEGORY_ENCHANTING"] = "附魔"
	L["ICON_CATEGORY_ENGINEERING"] = "工程学"
	L["ICON_CATEGORY_FIRST_AID"] = "急救"
	L["ICON_CATEGORY_FISHING"] = "钓鱼"
	L["ICON_CATEGORY_HERBALISM"] = "草药学"
	L["ICON_CATEGORY_INSCRIPTION"] = "铭文"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "珠宝加工"
	L["ICON_CATEGORY_LEATHERWORKING"] = "制皮"
	L["ICON_CATEGORY_MINING"] = "采矿"
	L["ICON_CATEGORY_SKINNING"] = "剥皮"
	L["ICON_CATEGORY_TAILORING"] = "裁缝"

	L["ICON_CATEGORY_DRINK"] = "饮料"
	L["ICON_CATEGORY_FOOD"] = "食物"
	L["ICON_CATEGORY_MOUNT"] = "坐骑"
	L["ICON_CATEGORY_PET"] = "伙伴"
	L["ICON_CATEGORY_POTION"] = "药水"
	L["ICON_CATEGORY_TRADE_GOODS"] = "贸易品"
	L["ICON_CATEGORY_HOUSING"] = "住宅"
	L["ICON_CATEGORY_PROFESSION"] = "专业技能"
	L["ICON_CATEGORY_ARMOR"] = "护甲"
	L["ICON_CATEGORY_WEAPON"] = "武器"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "职业"
	L["ICON_CATEGORY_CULTURE"] = "文化"

	L["ICON_CATEGORY_ALLWEAPONS"] = "所有武器"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "近战武器"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "远程武器"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "物品栏栏位"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "阵营"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "所有专业"
	L["ICON_CATEGORY_ALLITEMS"] = "所有物品"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "其他阵营"
	L["ICON_CATEGORY_JEWELRY"] = "珠宝"
	L["UnknownIcon"] = "未知图标"
	L["FileID"] = "文件 ID: %s"

return end

if LOCALE == "zhTW" then
	-- Traditional Chinese translations go here
	L["TOC_Title"] = "圖示瀏覽器 (Icon Browser)"
	L["TOC_Notes"] = "用於巨集、銀行與塑形的圖示瀏覽器替代工具，含搜尋欄與預設過濾條件。"

	L["ICON_CATEGORY_DRACTHYR"] = "半龍人"
	L["ICON_CATEGORY_DRAENEI"] = "德萊尼"
	L["ICON_CATEGORY_DWARVEN"] = "矮人"
	L["ICON_CATEGORY_ELVEN"] = "精靈"
	L["ICON_CATEGORY_GNOMISH"] = "地精"
	L["ICON_CATEGORY_GOBLIN"] = "哥布林"
	L["ICON_CATEGORY_HARANIR"] = "哈拉尼爾"
	L["ICON_CATEGORY_HUMAN"] = "人類"
	L["ICON_CATEGORY_ORCISH"] = "獸人"
	L["ICON_CATEGORY_PANDAREN"] = "熊貓人"
	L["ICON_CATEGORY_TAUREN"] = "牛頭人"
	L["ICON_CATEGORY_TROLL"] = "食人妖"
	L["ICON_CATEGORY_UNDEAD"] = "不死族"
	L["ICON_CATEGORY_VULPERA"] = "狐狸人"
	L["ICON_CATEGORY_WORGEN"] = "吉爾尼斯/狼人"

	L["ICON_CATEGORY_AXE"] = "斧"
	L["ICON_CATEGORY_DAGGER"] = "匕首"
	L["ICON_CATEGORY_FIST_WEAPON"] = "拳套"
	L["ICON_CATEGORY_MACE"] = "錘"
	L["ICON_CATEGORY_POLEARM"] = "長柄武器"
	L["ICON_CATEGORY_STAFF"] = "法杖"
	L["ICON_CATEGORY_SWORD"] = "劍"
	L["ICON_CATEGORY_WAND"] = "魔杖"
	L["ICON_CATEGORY_WARGLAIVE"] = "戰刃"
	
	L["ICON_CATEGORY_RANGED"] = INVTYPE_RANGED
	L["ICON_CATEGORY_AMMO"] = INVTYPE_AMMO
	L["ICON_CATEGORY_BOW"] = "弓"
	L["ICON_CATEGORY_CROSSBOW"] = "弩"
	L["ICON_CATEGORY_GUN"] = "槍械"
	L["ICON_CATEGORY_THROWN"] = "投擲武器"
	L["ICON_CATEGORY_CLOTH_ARMOR"] = "布甲"
	L["ICON_CATEGORY_LEATHER_ARMOR"] = "皮甲"
	L["ICON_CATEGORY_MAIL_ARMOR"] = "鎖甲"
	L["ICON_CATEGORY_PLATE_ARMOR"] = "鎧甲"
	L["ICON_CATEGORY_HEAD"] = INVTYPE_HEAD
	L["ICON_CATEGORY_NECK"] = INVTYPE_NECK
	L["ICON_CATEGORY_SHOULDERS"] = INVTYPE_SHOULDER
	L["ICON_CATEGORY_BACK"] = INVTYPE_CLOAK
	L["ICON_CATEGORY_CHEST"] = INVTYPE_CHEST
	L["ICON_CATEGORY_SHIRT"] = INVTYPE_BODY
	L["ICON_CATEGORY_TABARD"] = INVTYPE_TABARD
	L["ICON_CATEGORY_WRISTS"] = INVTYPE_WRIST
	L["ICON_CATEGORY_HANDS"] = INVTYPE_HAND
	L["ICON_CATEGORY_WAIST"] = INVTYPE_WAIST
	L["ICON_CATEGORY_LEGS"] = INVTYPE_LEGS
	L["ICON_CATEGORY_FEET"] = INVTYPE_FEET
	L["ICON_CATEGORY_RING"] = INVTYPE_FINGER
	L["ICON_CATEGORY_TRINKET"] = INVTYPE_TRINKET
	L["ICON_CATEGORY_OFF_HAND"] = INVTYPE_SHIELD
	L["ICON_CATEGORY_SHIELD"] = "盾牌"

	L["ICON_CATEGORY_ARCANE"] = SPELL_SCHOOL6_CAP
	L["ICON_CATEGORY_FEL"] = "魔化"
	L["ICON_CATEGORY_FIRE"] = SPELL_SCHOOL2_CAP
	L["ICON_CATEGORY_FROST"] = SPELL_SCHOOL4_CAP
	L["ICON_CATEGORY_HOLY"] = SPELL_SCHOOL1_CAP
	L["ICON_CATEGORY_NATURE"] = SPELL_SCHOOL3_CAP
	L["ICON_CATEGORY_SHADOW"] = SPELL_SCHOOL5_CAP
	L["ICON_CATEGORY_VOID"] = "虛無"

	L["ICON_CATEGORY_ALLIANCE"] = FACTION_ALLIANCE
	L["ICON_CATEGORY_HORDE"] = FACTION_HORDE

	L["ICON_CATEGORY_ALCHEMY"] = "鍊金術"
	L["ICON_CATEGORY_ARCHAEOLOGY"] = "考古學"
	L["ICON_CATEGORY_BLACKSMITHING"] = "鍛造"
	L["ICON_CATEGORY_COOKING"] = "烹飪"
	L["ICON_CATEGORY_ENCHANTING"] = "附魔"
	L["ICON_CATEGORY_ENGINEERING"] = "工程學"
	L["ICON_CATEGORY_FIRST_AID"] = "急救"
	L["ICON_CATEGORY_FISHING"] = "釣魚"
	L["ICON_CATEGORY_HERBALISM"] = "草藥學"
	L["ICON_CATEGORY_INSCRIPTION"] = "銘文學"
	L["ICON_CATEGORY_JEWELCRAFTING"] = "珠寶設計"
	L["ICON_CATEGORY_LEATHERWORKING"] = "製皮"
	L["ICON_CATEGORY_MINING"] = "採礦"
	L["ICON_CATEGORY_SKINNING"] = "剝皮"
	L["ICON_CATEGORY_TAILORING"] = "裁縫"

	L["ICON_CATEGORY_DRINK"] = "飲料"
	L["ICON_CATEGORY_FOOD"] = "食物"
	L["ICON_CATEGORY_MOUNT"] = "坐騎"
	L["ICON_CATEGORY_PET"] = "伙伴"
	L["ICON_CATEGORY_POTION"] = "藥水"
	L["ICON_CATEGORY_TRADE_GOODS"] = "貿易品"
	L["ICON_CATEGORY_HOUSING"] = "房屋系統"
	L["ICON_CATEGORY_PROFESSION"] = "專業技能"
	L["ICON_CATEGORY_ARMOR"] = "護甲"
	L["ICON_CATEGORY_WEAPON"] = "武器"

	L["ICON_CATEGORY_SPELLSABILITIES"] = TUTORIAL_TITLE6

	L["ICON_CATEGORY_ACHIEVEMENTS"] = ACHIEVEMENT_BUTTON

	L["ICON_CATEGORY_CLASSES"] = "職業"
	L["ICON_CATEGORY_CULTURE"] = "文化"

	L["ICON_CATEGORY_ALLWEAPONS"] = "所有武器"
	L["ICON_CATEGORY_MELEEWEAPONS"] = "所有近戰武器"
	L["ICON_CATEGORY_RANGEDWEAPONS"] = "遠程武器"
	L["ICON_CATEGORY_INVENTORYSLOTS"] = "物品欄欄位"

	L["ICON_CATEGORY_MAGIC"] = STRING_SCHOOL_MAGIC

	L["ICON_CATEGORY_FACTIONS"] = "陣營"
	L["ICON_CATEGORY_ALLPROFESSIONS"] = "所有專業"
	L["ICON_CATEGORY_ALLITEMS"] = "所有物品"

	L["ICON_CATEGORY_ITEMS"] = ITEMS

	L["ICON_CATEGORY_OTHER_FACTIONS"] = "其他陣營"
	L["ICON_CATEGORY_JEWELRY"] = "珠寶"
	L["UnknownIcon"] = "未知圖示"
	L["FileID"] = "檔案 ID：%s"

return end
